export class HeaderImgCount {
   static readonly Home = 3;
   static readonly Others = 1;
}
export class HomeOpinionsImgCount {
   static readonly MeltMeTender = 15;
   static readonly Argasinscy = 4;
   static readonly PaulinaPapiez = 5;
}
export class OfferImgCount {
   static readonly Food = 6;
   static readonly Product = 6;
   static readonly Reportage = 6;
}
export class PortfolioImgCount {
   static readonly Food = 40;
   static readonly Product = 40;
   static readonly Reportage = 40;
}
export type ImagePath =
| `logo/logo.png`
| `flagi/grecja.png`
| `flagi/japonia.png`
| `flagi/polska.png`
| `flagi/korea.png`
| `flagi/czechy.png`
| `flagi/turcja.png`
| `flagi/tajlandia.png`
| `flagi/wlochy.png`
| `flagi/dania.png`
| `miniaturki/ateny.jpg`
| `miniaturki/rodos.jpg`
| `miniaturki/santorini.jpg`
| `miniaturki/kreta.jpg`
| `miniaturki/symi.jpg`
| `miniaturki/delfy-arachova.jpg`
| `miniaturki/tokio.jpg`
| `miniaturki/osaka.jpg`
| `miniaturki/kioto.jpg`
| `miniaturki/wenecja.jpg`
| `miniaturki/bangkok.jpg`
| `miniaturki/phuket.jpg`
| `miniaturki/phiphi.jpg`
| `miniaturki/krabi.jpg`
| `miniaturki/seul.jpg`
| `miniaturki/busan.jpg`
| `miniaturki/torun.jpg`
| `miniaturki/wroclaw.jpg`
| `miniaturki/lodz.jpg`
| `miniaturki/krakow.jpg`
| `miniaturki/adrspach.jpg`
| `miniaturki/horsens.jpg`
| `miniaturki/side.jpg`
| `czechy/ardspach-1-1`
| `czechy/ardspach-1-2`
| `czechy/ardspach-1-3`
| `czechy/ardspach-1-4`
| `czechy/ardspach-2-1`
| `czechy/ardspach-2-2`
| `czechy/ardspach-2-3`
| `czechy/ardspach-2-4`
| `dania/horsens-1-1`
| `dania/horsens-1-2`
| `dania/horsens-1-3`
| `dania/horsens-1-4`
| `dania/horsens-2-1`
| `dania/horsens-2-2`
| `dania/horsens-2-3`
| `dania/horsens-2-4`
| `grecja/ateny-1-1`
| `grecja/ateny-1-2`
| `grecja/ateny-1-3`
| `grecja/ateny-1-4`
| `grecja/ateny-2-1`
| `grecja/ateny-2-2`
| `grecja/ateny-2-3`
| `grecja/ateny-2-4`
| `grecja/rodos-1-1`
| `grecja/rodos-1-2`
| `grecja/rodos-1-3`
| `grecja/rodos-1-4`
| `grecja/rodos-2-1`
| `grecja/rodos-2-2`
| `grecja/rodos-2-3`
| `grecja/rodos-2-4`
| `grecja/delfy-1-1`
| `grecja/delfy-1-2`
| `grecja/delfy-1-3`
| `grecja/delfy-1-4`
| `grecja/delfy-2-1`
| `grecja/delfy-2-2`
| `grecja/delfy-2-3`
| `grecja/delfy-2-4`
| `grecja/kreta-1-1`
| `grecja/kreta-1-2`
| `grecja/kreta-1-3`
| `grecja/kreta-1-4`
| `grecja/kreta-2-1`
| `grecja/kreta-2-2`
| `grecja/kreta-2-3`
| `grecja/kreta-2-4`
| `grecja/santorini-1-1`
| `grecja/santorini-1-2`
| `grecja/santorini-1-3`
| `grecja/santorini-1-4`
| `grecja/santorini-2-1`
| `grecja/santorini-2-2`
| `grecja/santorini-2-3`
| `grecja/santorini-2-4`
| `grecja/symi-1-1`
| `grecja/symi-1-2`
| `grecja/symi-1-3`
| `grecja/symi-1-4`
| `grecja/symi-2-1`
| `grecja/symi-2-2`
| `grecja/symi-2-3`
| `grecja/symi-2-4`
| `włochy/wenecja-1-1`
| `włochy/wenecja-1-2`
| `włochy/wenecja-1-3`
| `włochy/wenecja-1-4`
| `włochy/wenecja-2-1`
| `włochy/wenecja-2-2`
| `włochy/wenecja-2-3`
| `włochy/wenecja-2-4`
| `japonia/kioto-1-1`
| `japonia/kioto-1-2`
| `japonia/kioto-1-3`
| `japonia/kioto-1-4`
| `japonia/kioto-2-1`
| `japonia/kioto-2-2`
| `japonia/kioto-2-3`
| `japonia/kioto-2-4`
| `japonia/osaka-1-1`
| `japonia/osaka-1-2`
| `japonia/osaka-1-3`
| `japonia/osaka-1-4`
| `japonia/osaka-2-1`
| `japonia/osaka-2-2`
| `japonia/osaka-2-3`
| `japonia/osaka-2-4`
| `japonia/tokio-1-1`
| `japonia/tokio-1-2`
| `japonia/tokio-1-3`
| `japonia/tokio-1-4`
| `japonia/tokio-2-1`
| `japonia/tokio-2-2`
| `japonia/tokio-2-3`
| `japonia/tokio-2-4`
| `korea/busan-1-1`
| `korea/busan-1-2`
| `korea/busan-1-3`
| `korea/busan-1-4`
| `korea/busan-2-1`
| `korea/busan-2-2`
| `korea/busan-2-3`
| `korea/busan-2-4`
| `korea/seul-1-1`
| `korea/seul-1-2`
| `korea/seul-1-3`
| `korea/seul-1-4`
| `korea/seul-2-1`
| `korea/seul-2-2`
| `korea/seul-2-3`
| `korea/seul-2-4`
| `polska/krakow-1-1`
| `polska/krakow-1-2`
| `polska/krakow-1-3`
| `polska/krakow-1-4`
| `polska/krakow-2-1`
| `polska/krakow-2-2`
| `polska/krakow-2-3`
| `polska/krakow-2-4`
| `polska/lodz-1-1`
| `polska/lodz-1-2`
| `polska/lodz-1-3`
| `polska/lodz-1-4`
| `polska/lodz-2-1`
| `polska/lodz-2-2`
| `polska/lodz-2-3`
| `polska/lodz-2-4`
| `polska/torun-1-1`
| `polska/torun-1-2`
| `polska/torun-1-3`
| `polska/torun-1-4`
| `polska/torun-2-1`
| `polska/torun-2-2`
| `polska/torun-2-3`
| `polska/torun-2-4`
| `polska/wroclaw-1-1`
| `polska/wroclaw-1-2`
| `polska/wroclaw-1-3`
| `polska/wroclaw-1-4`
| `polska/wroclaw-2-1`
| `polska/wroclaw-2-2`
| `polska/wroclaw-2-3`
| `polska/wroclaw-2-4`
| `tajlandia/bangkok-1-1`
| `tajlandia/bangkok-1-2`
| `tajlandia/bangkok-1-3`
| `tajlandia/bangkok-1-4`
| `tajlandia/bangkok-2-1`
| `tajlandia/bangkok-2-2`
| `tajlandia/bangkok-2-3`
| `tajlandia/bangkok-2-4`
| `tajlandia/krabi-1-1`
| `tajlandia/krabi-1-2`
| `tajlandia/krabi-1-3`
| `tajlandia/krabi-1-4`
| `tajlandia/krabi-2-1`
| `tajlandia/krabi-2-2`
| `tajlandia/krabi-2-3`
| `tajlandia/krabi-2-4`
| `tajlandia/phi-phi-1-1`
| `tajlandia/phi-phi-1-2`
| `tajlandia/phi-phi-1-3`
| `tajlandia/phi-phi-1-4`
| `tajlandia/phi-phi-2-1`
| `tajlandia/phi-phi-2-2`
| `tajlandia/phi-phi-2-3`
| `tajlandia/phi-phi-2-4`
| `tajlandia/phuket-1-1`
| `tajlandia/phuket-1-2`
| `tajlandia/phuket-1-3`
| `tajlandia/phuket-1-4`
| `tajlandia/phuket-2-1`
| `tajlandia/phuket-2-2`
| `tajlandia/phuket-2-3`
| `tajlandia/phuket-2-4`
| `turcja/side-1-1`
| `turcja/side-1-2`
| `turcja/side-1-3`
| `turcja/side-1-4`
| `turcja/side-2-1`
| `turcja/side-2-2`
| `turcja/side-2-3`
| `turcja/side-2-4`